// Mock pet data for the platform
export const mockPets = [
  {
    id: '1',
    name: 'Buddy',
    breed: 'Golden Retriever',
    age: 3,
    gender: 'Male',
    species: 'Dog',
    image: 'https://images.unsplash.com/photo-1633722715463-d30628519b85?w=400&h=400&fit=crop',
    area: 'Mumbai',
    ownerPhone: '+91 9876543210',
    ownerEmail: 'john@example.com',
    type: 'match', // or 'sell'
  },
  {
    id: '2',
    name: 'Bella',
    breed: 'Siamese',
    age: 2,
    gender: 'Female',
    species: 'Cat',
    image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop',
    area: 'Bangalore',
    ownerPhone: '+91 9876543211',
    ownerEmail: 'jane@example.com',
    type: 'sell',
    price: 15000,
  },
  {
    id: '3',
    name: 'Charlie',
    breed: 'Labrador Retriever',
    age: 4,
    gender: 'Male',
    species: 'Dog',
    image: 'https://images.unsplash.com/photo-1625895917138-9eef77562a73?w=400&h=400&fit=crop',
    area: 'Delhi',
    ownerPhone: '+91 9876543212',
    ownerEmail: 'mike@example.com',
    type: 'match',
  },
  {
    id: '4',
    name: 'Luna',
    breed: 'Persian',
    age: 1,
    gender: 'Female',
    species: 'Cat',
    image: 'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=400&h=400&fit=crop',
    area: 'Pune',
    ownerPhone: '+91 9876543213',
    ownerEmail: 'sarah@example.com',
    type: 'sell',
    price: 20000,
  },
  {
    id: '5',
    name: 'Max',
    breed: 'German Shepherd',
    age: 5,
    gender: 'Male',
    species: 'Dog',
    image: 'https://images.unsplash.com/photo-1568572933382-74d440642117?w=400&h=400&fit=crop',
    area: 'Hyderabad',
    ownerPhone: '+91 9876543214',
    ownerEmail: 'david@example.com',
    type: 'match',
  },
  {
    id: '6',
    name: 'Whiskers',
    breed: 'Bengal',
    age: 3,
    gender: 'Male',
    species: 'Cat',
    image: 'https://images.unsplash.com/photo-1606214174585-fe31582dc1d8?w=400&h=400&fit=crop',
    area: 'Chennai',
    ownerPhone: '+91 9876543215',
    ownerEmail: 'emma@example.com',
    type: 'sell',
    price: 25000,
  },
];

export const mockChatMessages = [
  { id: '1', sender: 'You', text: 'Hi, is Buddy still available?', timestamp: new Date(Date.now() - 3600000) },
  { id: '2', sender: 'John Doe', text: 'Yes, Buddy is available! Would you like to know more?', timestamp: new Date(Date.now() - 3500000) },
  { id: '3', sender: 'You', text: 'What\'s his temperament like?', timestamp: new Date(Date.now() - 3400000) },
  { id: '4', sender: 'John Doe', text: 'He\'s very friendly and loves to play fetch. Great with kids!', timestamp: new Date(Date.now() - 3300000) },
  { id: '5', sender: 'You', text: 'That sounds perfect! When can I meet him?', timestamp: new Date(Date.now() - 3200000) },
];

export const species = ['Dog', 'Cat', 'Rabbit', 'Hamster', 'Bird', 'Guinea Pig'];
export const dogBreeds = ['Golden Retriever', 'Labrador', 'German Shepherd', 'Pug', 'Bulldog', 'Beagle'];
export const catBreeds = ['Siamese', 'Persian', 'Bengal', 'Maine Coon', 'Ragdoll', 'British Shorthair'];
